---
kind: pipeline
type: ssh
name: deploy

server:
    host:
      from_secret: host
    user:
      from_secret: username
    ssh_key:
      from_secret: ssh_key

clone:
    disable: true

trigger:
    branch:
      - master

steps:
    - name: deploy
      commands:
        - cd /opt/services/clinte
        - sudo -Hu services git pull origin master
        - sudo -Hu services sh -c 'PATH="/opt/services/.cargo/bin:$PATH" make'
        - sudo -Hu root make install
