language: rust

rust:
  - stable

os: 
  - linux

dist: bionic

env:
  - RUST_TEST_THREADS=1

before_script:
    - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

script:
    - cargo check
    - cargo tarpaulin --out Xml
    - bash <(curl -s https://codecov.io/bash)
